### ISSUE TITLE
define CSS classes pull-left and pull-right for Font Awesome 5

### ISSUE THREAD

**Issue by stephanrauh** [TheCoder4eu/BootsFaces-OSP#1088]
The complete set of classes should look like so:

```CSS
.fa.pull-left,
.fas.pull-left,
.far.pull-left,
.fab.pull-left,
.fal.pull-left {
  margin-right: .3em;
}
.fa.pull-right,
.fas.pull-right,
.far.pull-right,
.fal.pull-right,
.fab.pull-right {
  margin-left: .3em;
}
```
