### ISSUE TITLE
CSS class styling doesn't work as expected because overridden by default style, work if using inline style

### ISSUE THREAD

**Issue by rizagp** [TheCoder4eu/BootsFaces-OSP#466]
Hello BootsFaces team,

Thank you for all the hardwork and great components. For styling I still have some problems:
The inline styling work, but class not work because overridden by Bootstrap class

So in short this one work:
```xml
<b:navBar fluid="true" brand-href="#" style="margin-bottom: 0px;" 
      brand-style="padding:0px;" brand-img="#{resource['images/logo_bpjstk.png']}" 
      brand-img-style="height:100%;padding:10px;width:auto;" alt="BPJS Ketenagakerjaan" 
      inverse="true">
</b:navBar>
```

But this one doesn't work as expected:
```xml
<b:navBar fluid="true" brand-href="#" styleClass="navbar-style"   
     brandStyleClass="brand-style" brand-img="#{resource['images/logo_bpjstk.png']}" 
     brandImgStyleClass="brand-img-style" alt="BPJS Ketenagakerjaan" inverse="true">
</b:navBar>
```

The padding still being overridden by Bootstrap navbar style padding, so the image becoming so small

The css is like this : 
```css
.navbar-style {
    margin-bottom: 0px;
}

.brand-style {
    padding:0px;
}

.brand-img-style {
    height:100%;
    padding:10px;
    width:auto;
}
````
Maybe there is workaround? Or this is a bug?
