### ISSUE TITLE
showCollapseLink for b:panel not working

### ISSUE THREAD

**Issue by michbeck100** [TheCoder4eu/BootsFaces-OSP#579]
As you can see at http://showcase.bootsfaces.net/layout/panels.jsf under "Collapsible panels indicator", the attribute showCollapseLink doesn't seem to do anything. I've seen the same effect in my project.

**Comment by stephanrauh** [comment]
@TheCoder4eu The indicator was defined in the bs-panels.less file. However, this file isn't there anymore. Do you know what happened to it? This is what it looked like (minus the comments):

```css
@import "variables.less";
@import "extra-variables.less";
@import "mixins.less";
@import "panels.less";

/* Collapsible panels */
.panel-heading a:after {
    font-family:'Glyphicons Halflings';
    content:"\e114";
    float: right;
    color: grey;
}
.panel-heading a.collapsed:after {
    content:"\e080";
}
a.panel-title-link {
	outline: thin dotted rgba(255, 255, 255, 0.3);
    outline-offset: 3px;
}
```
