### ISSUE TITLE
how to center the title of the panel?

### ISSUE THREAD

**Issue by wccmachado** [TheCoder4eu/BootsFaces-OSP#644]
I would like to know how to center the title of the panel.

**Comment by stephanrauh** [comment]
Try
```
<b:panel title-style="text-align:center">`
```
Alternatively, you can define a CSS rule like
```CSS
.panel-heading {
   text-align: center;
}
```

Please report back if this solves your problem, so we can close the ticket. 

Thanks in advance!
Stephan
