### ISSUE TITLE
b:alert without severity has no severity at all

### ISSUE THREAD

**Issue by ggam** [TheCoder4eu/BootsFaces-OSP#677]
`b:alert` documentation says the default severity is "warning", but when no severity is set, the alert is rendered without styles (as BootStrap says).

Seems like it just adds the CSS class `alert alert-{severity}`. Also, the documentation could be improved to clarify that custom severities can be used.

**Comment by stephanrauh** [comment]
What do you mean by custom severities? Something like that?

```less
.alert-pink {
  .alert-variant(#FF1493; #FF1493; #FF1493);
}

.alert-variant(@background; @border; @text-color) {
  background-color: @background;
  border-color: @border;
  color: @text-color;

  hr {
    border-top-color: darken(@border, 5%);
  }
  .alert-link {
    color: darken(@text-color, 10%);
  }
}
```
