### ISSUE TITLE
OmniFaces CombinedResourceHandler problem with Glyphicons

### ISSUE THREAD

**Issue by ggam** [TheCoder4eu/BootsFaces-OSP#688]
Glyphicons don't work when that ResourceHandler. The documentation has it disabled but enabling it reveals the problem.

Happens with OmniFaces 2.6.1 but also with the patched 1.12 version the web uses.

**Comment by stephanrauh** [comment]
The problem is that the regular CSS files are in a subfolder. The combined CSS file of OmniFaces is one folder up. So the relative paths pointing to the Glyphicons font points to the wrong direction after being combined by OmniFaces.

**Comment by stephanrauh** [comment]
I've opened a bug report on the OmniFaces repository: https://github.com/omnifaces/omnifaces/issues/371.

**Comment by ggam** [comment]
I'm not that sure this is an OmniFaces problem at all.

Our CSS use be using #{resource['boostfaces/xxx.tif']} references so that
JSF can replace it to whatever the final location is.

We should first check if that solves the problem.

**Comment by stephanrauh** [comment]
Have a look at the `bs-core.css` files:

```css
@font-face {
	font-family: 'Glyphicons Halflings';
	src: url('../../../fonts/glyphicons-halflings-regular.eot');
	src: url('../../../fonts/glyphicons-halflings-regular.eot?#iefix')
		format('embedded-opentype'),
		url('../../../fonts/glyphicons-halflings-regular.woff2')
		format('woff2'),
		url('../../../fonts/glyphicons-halflings-regular.woff') format('woff'),
		url('../../../fonts/glyphicons-halflings-regular.ttf')
		format('truetype'),
		url('../../../fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular')
		format('svg');
}
```
